website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User,Posts
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from . import db
from .models import Posts
import os
from werkzeug.utils import secure_filename
from flask import current_app
from sqlalchemy.sql.expression import func
from sqlalchemy import asc, desc


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('auth.profile'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name,last_name=last_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.profile'))

    return render_template("sign_up.html", user=current_user)



@auth.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    return render_template("profile.html",user=current_user)

@auth.route('/editprofile', methods=['GET', 'POST'])
@login_required
def editprofile():
    id = current_user.id
    userloggedin = User.query.get_or_404(id)
    if request.method == "POST":
        userloggedin.website = request.form.get('website')
        userloggedin.instagram = request.form.get('instagram')
        userloggedin.bio = request.form.get('bio')
        file = request.files['file']
        userloggedin.image = file.filename
        if not userloggedin.bio:
            flash('Bio cannot be empty', category='error')
        else:
            db.session.commit()
            flash('bio updated!', category='success')
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            flash('Profile picture updated succesfully')
            return redirect(url_for('auth.profile'))
    return render_template("X/editprofile.html",user=current_user)



@auth.route('/create-article', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == "POST":
        title = request.form.get('title')
        preview = request.form.get('preview')
        # content = request.form.get('content')
        content = request.form.get('ckeditor')
        file = request.files['file']
        img_name = file.filename
        author = current_user.id
        category = request.form.get('category')
        if not content:
            flash('Post cannot be empty', category='error')
        else:
            post = Posts(title=title,preview=preview, content=content, image=img_name, author=author,category=category)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            #print('upload_image filename: ' + filename)
            flash('Image successfully uploaded and displayed below')
            return render_template('X/createarticle.html',user=current_user)
    return render_template("X/createarticle.html",user=current_user)



@auth.route('/update-article/<id>', methods=['GET', 'POST'])
@login_required
def update(id):
    article = Posts.query.get_or_404(id)
    if not article:
        flash("Post does not exist.", category='error')
    else:
        if request.method == "POST":
            article.title = request.form.get('title')
            article.preview = request.form.get('preview')
            article.content = request.form.get('ckeditor')
            file = request.files['file']
            article.image = file.filename
            article.author = current_user.id
            article.category = request.form.get('category')
            if not article.content:
                flash('Post cannot be empty', category='error')
            else:
                db.session.commit()
                flash('Post updated successfully!', category='success')
                if not file:
                    return redirect(url_for('auth.deletev2'))
                else:
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
                    flash('Image successfully updated ')
                    return redirect(url_for('auth.deletev2'))
    return render_template("X/editarticle.html",user=current_user, article=article)



@auth.route('/delete/<id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    post = Posts.query.filter_by(id=id).first()
    if not post:
        flash("Post does not exist.", category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted.', category='success')
    return redirect(url_for('auth.deletev2'))


displayed_posts = 9

@auth.route('/delete', methods=['GET', 'POST'])
@login_required
def deletev2():
    if current_user.is_authenticated == False:
        return redirect(url_for('views.home'))
    else:
        sort = "new"
        posts = Posts.query.all()
        page = request.args.get('page', 1, type=int)
        posts = Posts.query.order_by(Posts.pub_date.desc()).paginate(page=page, per_page=displayed_posts)
        return render_template("X/delete.html",user=current_user, posts=posts, sort=sort)




@auth.route('/delete/sorted_by_oldest', methods=['GET', 'POST'])
def oldest():
    sort = "oldest"
    page = request.args.get('page', 1, type=int)
    posts = Posts.query.paginate(page=page, per_page=displayed_posts)
    return render_template("X/delete.html",user=current_user, posts=posts, sort=sort)

website/views.py
from datetime import date
from operator import pos
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from . import db
from .models import Rating, User,Posts
import random
import os
from werkzeug.utils import secure_filename
from flask import current_app
from sqlalchemy.sql.expression import func
from sqlalchemy import asc, desc



views = Blueprint('views', __name__)
displayed_posts = 9

@views.route("/")
@views.route('/home', methods=['GET', 'POST'])
def home():
    slides_article = Posts.query.order_by(func.random()).limit(3).all()
    sort = "new"
    page = request.args.get('page', 1, type=int)
    posts = Posts.query.order_by(Posts.pub_date.desc()).paginate(page=page, per_page=displayed_posts)
    return render_template("index.html",user=current_user,posts=posts, sort=sort,slides_article=slides_article)

@views.route('/home/sorted_by_oldest', methods=['GET', 'POST'])
def oldest():
    page = request.args.get('page', 1, type=int)
    posts = Posts.query.paginate(page=page, per_page=displayed_posts)
    return render_template("index.html",user=current_user,posts=posts)



@views.route("/search", methods=['POST', 'GET'])
def search():
    search = request.args.get('search')
    if search:
        posts= Posts.query.filter(Posts.title.contains(search) | 
        Posts.content.contains(search))
        return render_template("search.html", search=search, posts=posts, user=current_user)
    else:
        posts = Posts.query.all()
        return render_template("search.html", search=search, posts=posts, user=current_user)
        



@views.route('/article/<id>', methods=['GET', 'POST'])
def article(id):
    Post = Posts.query.filter_by(id=id).first()
    Author = User.query.filter_by(id=Post.author).first()
   
    if request.method == "POST":
        selectedValue = request.form['rating']
        rating = Rating(rating=selectedValue, articleId=id)
        db.session.add(rating)
        db.session.commit()
    return render_template("article.html",user=current_user, post=Post , Author=Author)



@views.route('/author/<id>', methods=['GET', 'POST'])
def author(id):
    posts= Posts.query.filter(Posts.author.contains(id)).order_by(Posts.pub_date.desc()).limit(9).all()
    Author = User.query.filter_by(id=id).first()
    return render_template("author.html",user=current_user, posts=posts , Author=Author)

website/templates/article.html
{% extends 'base.html' %}
{% block title %} {{ post['title'] }} {% endblock %}
{%block content%}
<div class="blog-post w-100 article-title-wrapper">
    <div class="wrapper">
        <img class="first-image" src="/static/articleimg/{{ post['image']  }}" alt=" ">
        <div class="article-title w-100 text-center">
            <h3 class="blog-post-title">{{ post['title'] }}</h3>
            <p class="blog-post-meta">{{ post.pub_date.strftime('%Y-%m-%d') }} by 
                <a href="{{url_for('views.author', id = Author['id'] )}}" class="text-danger">
                    {{Author.first_name}} {{Author.last_name }}</a></p>
        </div>
    </div>
</div>




<div class="container-fluid">

        <div class="container"  >
            <div class="w-100 border-bottom border-secondary pb-5 p-lg-5 article-wrapper" >
                <span class="text-justify">{{ post['content'] | safe }}</span>
            </div>

            <div class="container text-center justify-content-center border-bottom border-secondary pb-5" >
                <h4 class="mt-4 text-secondary"> How do you rate this article?</h4>
                <div class="container">
                <form method="post" >
                    <div class="starrating risingstar d-flex justify-content-center flex-row-reverse"> 
                        <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="5 star"></label>
                        <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="4 star"></label>
                        <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="3 star"></label>
                        <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="2 star"></label>
                        <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="1 star"></label>
                    </div>
                    <button class="btn-danger" type="submit" > Submit</button>
                </form>
              </div>	
            </div>
            <!-- TODO: comments sectionm -->
            <!-- <div class="container sign-up">
                {% for message in get_flashed_messages() %}
                <div class="container text-danger">{{ message }}</div>
                {% endfor %}   
                
                <form class="w-100 mt-5" method="POST" enctype="multipart/form-data">
                    <h4 class="mb-2 w-100 text-center">Add comment</h4> 
                    <div class="form-outline mb-4">
                        <label class="form-label" for="comment">*Comment</label>
                        <textarea name="comment"
                        placeholder="Write your comment here...."
                        rows="5"
                        class="form-control text-white bg-dark rounded-0"
                        id="comment"
                        onclick="display_rest()"
                        ></textarea>
                    </div>

                <div id="restcomment" style="display: none;">
                    <div class="form-outline mb-4">
                    <label class="form-label" for="Name">Name</label>
                    <input type="text" name="Name"
                           placeholder="Post title"
                           class="form-control text-white bg-dark rounded-0"
                           id="Name"></input>
                    </div>
                    <div class="form-outline mb-4">
                        <label class="form-label" for="preview">E-mail</label>
                        <input type="text" name="preview"
                               placeholder="Post title"
                               class="form-control text-white bg-dark rounded-0"
                               id="preview"></input>
                        </div>
                </div>
                    <button type="submit" class="btn btn-outline-danger rounded-0 btn-block mb-4">Submit</button>
                </form>
            </div>
        </div> -->

</div>

</div>

<script>
function display_rest() {
  var x = document.getElementById("restcomment");
  if (x.style.display === "none") {
    x.style.display = "block";
  }
   else {
    x.style.display = "none";
  }
}
</script>



{% endblock %}

website/templates/author.html
{% extends 'base.html' %}
{% block title %} Blog posts {% endblock %}
{%block content%}



 <div class="container">
        <div class="card mb-4">
          <div class="card-body text-center">
            <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4">
                    {% if not Author.image %}
                    <img src="/static/icons/profile_blank.png" alt="Profile Picture"
                      class="rounded-circle img-fluid" style="height: 150px;">
                    {% else %}
                    <img src="/static/articleimg/{{Author.image}}" alt="avatar"
                    class="rounded-circle img-fluid profile-pic" >
                    {% endif %}
                </div>
                <div class="col-lg-8">
                    <h5 class="my-3">{{ Author.first_name }} {{ Author.last_name }}</h5>
                    <p class="text-muted mb-1">{{ Author.bio }}</p>
                </div>
            </div>
           
            
          </div>
        </div>
</div>





<div class="container border-bottom " style="padding:10px ;">
      <h5 class="d-inline align-content-center">Latest articles posted by: {{Author.first_name}} {{ Author.last_name }}</h5>
      <div class="btn-group d-inline float-right">
        <button type="button" class="btn btn-sm btn-outline-danger rounded-0 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort by
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <button class="dropdown-item" type="button">Newest</button>
        </div>
      </div>
</div>


<div class="container" style="margin-top:5px ;">



      <section class="cards" >
        {% for post in posts %}
       
        <div class="card" onclick="">
          <a href="article/{{post['id']}}">
          <div class="card__image-container rounded-bottom">
            <img
            src="/static/articleimg/{{ post['image']  }}"
            />
          </div>
          <div class="card__content">
            <p class="card__title text--medium ">
              {{ post['title'] }}
            </p>
            <div class="card__info ">
              {{ post['preview'] }}
            </div>
          </div>
        </a>
        </div>
        {%endfor%}
      </section>





</div>
</div>
{%endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- <link rel="stylesheet" href="static/stylesheets/index.css"  />
    <link rel="stylesheet" href="static/stylesheets/navigation.css" />
    <link rel="stylesheet" href="static/stylesheets/footer.css" /> -->
    <link rel="icon" href="{{url_for('static', filename = 'icons/icons8-gear-30.png') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{url_for('static', filename = 'stylesheets/index.css') }}" />
    <link rel="stylesheet" href="{{url_for('static', filename = 'stylesheets/navigation.css') }}" />
    <link rel="stylesheet" href="{{url_for('static', filename = 'stylesheets/footer.css') }}" />
    <link rel="stylesheet" href="{{url_for('static', filename = 'stylesheets/article.css') }}" />
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <!-- <link rel="stylesheet" href="{{url_for('static', filename = 'stylesheets/bootstrap/css/bootstrap.min.css') }}" /> -->
    <title>{% block title %} {% endblock %}</title>
</head>

<body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>


    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand text-white logo" href="/"><img
                src="{{url_for('static', filename = 'icons/icons8-gear-30.png') }}" width="30" height="30"
                class="d-inline-block align-top" alt="">
            GEARATIO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse  justify-content-end text-white" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="/profile">Account</a>
                </li>
                {%endif%}
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Arduino</a>
                        <a class="dropdown-item" href="#">RasberryPi</a>
                        <a class="dropdown-item" href="#">Mechanics</a>
                        <a class="dropdown-item" href="#">Electronics</a>
                    </div>
                </li> -->
                <li class="nav-item active">
                    <a class="nav-link" href="blog"></a>
                </li>
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="logout">Logout
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                            class="bi bi-box-arrow-in-right" viewBox="0 0 16 16" alt="Login">
                            <path fill-rule="evenodd"
                                d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z" />
                            <path fill-rule="evenodd"
                                d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                        </svg>
                    </a>
                    {% else %}
                    <!-- Default dropleft button -->
                    <div class="container-fluid">
                        <form class="d-flex d-flex align-items-center" method="GET"
                            action="{{ url_for('views.search') }}">
                            <input class="form-control me-2 btn-outline-dark rounded-0" type="text" placeholder="Search"
                                aria-label="Search" style="font-size:12px ;" name="search">
                            <button class="btn " type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white"
                                    class="bi bi-search" viewBox="0 0 16 16">
                                    <path
                                        d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                </svg>
                            </button>
                        </form>
                    </div>
                    {% endif %}
                </li>

            </ul>
        </div>
    </nav>


    {% block content %} {% endblock %}

    <footer>
        <span class="border-shape"></span>
        <div class="bottom_content">
            <section>
                <a href="#"><i class="fas fa-envelope"></i></a>
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </section>
        </div>
        <div class="copyright">
            Copyright © 2022 ELECTROBLOG.COM - All rights reserved
        </div>
    </footer>
</body>

</html>

website/templates/profile.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
<div class="container text-danger">{{ message }}</div>
{% endfor %}

<div class="container">
    <section style="background-color: rgb(0, 0, 0);">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        {% if not user.image %}
                        <img src="/static/icons/profile_blank.png" alt="avatar"
                            class="rounded-circle img-fluid profile-pic">
                        {% else %}
                        <img src="/static/articleimg/{{user.image}}" alt="avatar"
                            class="rounded-circle img-fluid profile-pic ">
                        {% endif %}
                        <h5 class="my-3">{{ user.first_name }} {{ user.last_name }}</h5>
                        <p class="text-muted mb-1">{{ user.bio }}</p>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                        <ul class="list-group list-group-flush rounded-3">
                            <li
                                class="list-group-item d-flex justify-content-between align-items-center p-3 bg-transparent">
                                <i class="fas fa-globe fa-lg text-warning"></i>
                                <p class="mb-0">{{ user.website }}</p>
                            </li>
                            <li
                                class="list-group-item d-flex justify-content-between align-items-center p-3 bg-transparent">
                                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                                <p class="mb-0">{{ user.instagram }}</p>
                            </li>
                        </ul>
                    </div>
                </div>


            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Full Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.first_name }} {{ user.last_name }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{% print(user.email) %}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Phone</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"> --------------</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <ul class="list-group ">
                                    <li class="list-group-item bg-transparent text-center"><a class="links"
                                            href="{{ url_for('auth.editprofile') }}"><button type="button"
                                                class="btn btn-outline-danger w-75 align-content-center">Edit
                                                profile</button></a></li>
                                    <li class="list-group-item bg-transparent text-center"><a
                                            href="{{ url_for('auth.create') }}"><button type="button"
                                                class="btn btn-outline-danger w-75">Create Article</button></a></li>
                                    <li class="list-group-item bg-transparent text-center"><a
                                            href="{{ url_for('auth.deletev2') }}"><button type="button"
                                                class="btn btn-outline-danger w-75">Delete/Edit Article</button></a></li>
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project
                                    Status
                                </p>
                                <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                                        aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                                        aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                                        aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                                        aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                                <div class="progress rounded mb-2" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                                        aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
</section>
</div>


{% endblock %}